# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
resources:
  webhooks:
    - webhook: Incoming         ### Webhook name
      connection: Incoming    ### Incoming webhook service connection name

variables:
  ORG_NAME: 'gustavopintari0575'
  PROJECT_NAME: 'gustavopintari'
  REPO_NAME: 'AdvancedApexSpecialistSuperBadge'
  BRANCH_PREFIX: 'f-'
  
steps:
- checkout: self
  persistCredentials: true
  
- script: |
    if [ -z "$GH_TOKEN" ]; then
        echo "❌ GH_TOKEN não está definido!"
        exit 1
    else
        echo "✅ GH_TOKEN está definido."
    fi
  env:
    GH_TOKEN: $(Secrets.Secrets)
  displayName: "Verificar se GH_TOKEN está definido"
  
- script: |
    if gh auth status &> /dev/null; then
        echo "✅ Autenticado no GitHub CLI."
    else
        echo "❌ NÃO autenticado no GitHub CLI."
        exit 1  # Opcional: falha o job se não estiver autenticado
    fi
  displayName: "Verificar autenticação no GitHub CLI"
  
- script: |
    echo "Criando a branch..."
    WORK_ITEM_ID=${{ parameters.Incoming.resource.id }}
    BRANCH_NAME=13

  displayName: 'Criar nova branch no Git'