# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
resources:
  webhooks:
    - webhook: Incoming         ### Webhook name
      connection: Incoming    ### Incoming webhook service connection name

variables:
  ORG_NAME: 'gustavopintari0575'
  PROJECT_NAME: 'gustavopintari'
  REPO_NAME: 'AdvancedApexSpecialistSuperBadge'
  BRANCH_PREFIX: 'f-'
  
steps:
- checkout: self
  persistCredentials: true
  
- script: |
    if command -v gh &> /dev/null; then
        echo "GitHub CLI (gh) está instalado."
    else
        echo "GitHub CLI (gh) NÃO está instalado."
    fi
  displayName: "Verificar instalação do GitHub CLI no Linux/macOS"
  
- script: |
    echo "Criando a branch..."
    WORK_ITEM_ID=${{ parameters.Incoming.resource.id }}
    BRANCH_NAME=13

  displayName: 'Criar nova branch no Git'