# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
resources:
  webhooks:
    - webhook: Incoming         ### Webhook name
      connection: Incoming    ### Incoming webhook service connection name
  repositories:
    - repository: AdvancedApexSpecialistSuperBadge
      name: GustavoPintari/AdvancedApexSpecialistSuperBadge
      type: git

variables:
  ORG_NAME: 'gustavopintari0575'
  PROJECT_NAME: 'gustavopintari'
  REPO_NAME: 'AdvancedApexSpecialistSuperBadge'
  BRANCH_PREFIX: 'f-'
  
steps:
- checkout: self
  
- script: echo ${AZURE_DEVOPS_CLI_PAT} | az devops login
  env:
    AZURE_DEVOPS_CLI_PAT: $(System.AccessToken)
  displayName: 'Login Azure DevOps Extension'
  
- bash:
    az repos list --org https://dev.azure.com/$(ORG_NAME) --project $(PROJECT_NAME) --debug
  env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

- script: |
    echo "Criando a branch..."
    WORK_ITEM_ID=${{ parameters.Incoming.resource.id }}
    BRANCH_NAME=$(BRANCH_PREFIX)/WorkItem-$WORK_ITEM_ID

    echo "Branch a ser criada: $BRANCH_NAME"

    az devops logout
  displayName: 'Criar nova branch no Git'