trigger: none
resources:
  webhooks:
    - webhook: AutoBranch     ### Webhook name
      connection: AutoBranch  ### Incoming webhook service connection name

variables:
  - group: GitHub Pipeline
  
steps:
- checkout: self
  persistCredentials: true
  
- script: |
    echo "${MY_JSON}"
  env:
    MY_JSON: ${{ convertToJson(parameters) }}
  displayName: "Resource json"

- script: |
    path='${{ convertToJson(parameters.AutoBranch.resource) }}'
    
    workItemId=$(echo "$path" | jq -r '.id')
    workItemType=$(echo "$path" | jq -r '.fields["System.WorkItemType"]')
    parentWorkItemId=$(echo "$path" | jq -r '.fields["System.Parent"] // empty')

    echo "WORK_ITEM_ID=${workItemId}"
    echo "WORK_ITEM_TYPE=${workItemType}"
    echo "PARENT_WORK_ITEM_ID=${parentWorkItemId}"

    echo "##vso[task.setvariable variable=WORK_ITEM_ID]${workItemId}"
    echo "##vso[task.setvariable variable=WORK_ITEM_TYPE]${workItemType}"
    echo "##vso[task.setvariable variable=PARENT_WORK_ITEM_ID]${parentWorkItemId}" 
  env:
    EVENT_TYPE: ${{ parameters.AutoBranch.eventType }}
    RESOURCE_PATH: ${{ convertToJson(parameters.AutoBranch.resource) }}
  displayName: "Set global variables"

- script: |
    gh auth status
  env:
    GITHUB_TOKEN: $(GH_TOKEN)
  displayName: "Check Github authentication"
  
- script: |
    git config --global user.name $(GIT_USER_NAME)
    git config --global user.email $(GIT_USER_EMAIL)
  displayName: "Configure Git identity"

- script: |
    baseBrach=$(BASE_BRANCH)
    prTitle="AB#$WORK_ITEM_ID"

    if [[ "$WORK_ITEM_TYPE" == "Feature" ]]; then
      branchPrefix="F-"
    else
      if [[ -z "$PARENT_WORK_ITEM_ID" ]]; then
        exit 1
      fi 

      parentBranch="F-${PARENT_WORK_ITEM_ID}"

      if ! git ls-remote --exit-code --heads origin $parentBranch > /dev/null; then
        echo "##vso[task.logissue type=error]Exit on Work item $WORK_ITEM_ID - Parent work item branch not found."
        exit 1
      fi 

      branchPrefix="T-"
      if [[ "$WORK_ITEM_TYPE" == "Impedimento" ]]; then
        branchPrefix="I-"
      fi

      prTitle="Fixed ${prTitle}"
      baseBrach="F-${PARENT_WORK_ITEM_ID}"
    fi

    newBranch="${branchPrefix}${WORK_ITEM_ID}"
    
    git fetch origin $baseBrach

    git checkout -b $newBranch origin/$baseBrach
    git push origin $newBranch

    if [[ "$MAKE_PR" == "true" ]]; then
      echo "Este é um arquivo criado automaticamente pela pipeline na branch $newBranch" > pipeline.txt
      
      git add pipeline.txt
      git commit -m "Pipeline"
      git push origin $newBranch

      gh pr create --base "$baseBrach" --head "$newBranch" --title "$prTitle" --body "Azure devops"
    fi
  env:
    GITHUB_TOKEN: $(GH_TOKEN)
  displayName: "Create branch and PR"