# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
resources:
  webhooks:
    - webhook: Incoming         ### Webhook name
      connection: Incoming    ### Incoming webhook service connection name

variables:
  ORG_NAME: 'gustavopintari0575'
  PROJECT_NAME: 'gustavopintari'
  REPO_NAME: 'AdvancedApexSpecialistSuperBadge'
  BRANCH_PREFIX: 'feature'
  
steps:
- checkout: self
  persistCredentials: true

# - script: az config set extension.use_dynamic_install=yes_without_prompt
#   displayName: 'Allow extensions'
- script: az devops configure --defaults organization="https://dev.azure.com/$ORG_NAME" project= "$PROJECT_NAME"
  displayName: 'Config'

- script: echo $(System.AccessToken) | az devops login
  displayName: 'Login to DevOps'
  
- script: echo az repos list --org "https://dev.azure.com/$ORG_NAME" --project "$PROJECT_NAME" | teste
  displayName: 'Repo list'

- script: |
    echo "Criando a branch..."
    WORK_ITEM_ID=${{ parameters.Incoming.resource.id }}
    BRANCH_NAME=$(BRANCH_PREFIX)/WorkItem-$WORK_ITEM_ID

    echo "Branch a ser criada: $BRANCH_NAME"

    az repos ref create \
      --name "refs/heads/$BRANCH_NAME" \
      --object-id "$WORK_ITEM_ID" \
      --organization "https://dev.azure.com/$ORG_NAME" \
      --project "$PROJECT_NAME" \
      --repository "$REPO_NAME"
  displayName: 'Criar nova branch no Git'