# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
resources:
  webhooks:
    - webhook: Incoming         ### Webhook name
      connection: Incoming    ### Incoming webhook service connection name

variables:
  ORG_NAME: 'gustavopintari0575'
  PROJECT_NAME: 'gustavopintari'
  REPO_NAME: 'AdvancedApexSpecialistSuperBadge'
  BRANCH_PREFIX: 'f-'
  
steps:
- checkout: self
  persistCredentials: true
  
- script: |
    az cache purge

    echo $(System.AccessToken) | az devops login --organization https://dev.azure.com/$(ORG_NAME) --allow-no-subscriptions --verbose

    az devops configure -d organization="https://dev.azure.com/$ORG_NAME" project="$PROJECT_NAME"

    az repos list --org https://dev.azure.com/$(ORG_NAME) --project $(PROJECT_NAME) --debug
  displayName: 'Repo list'

- script: |
    echo "Criando a branch..."
    WORK_ITEM_ID=${{ parameters.Incoming.resource.id }}
    BRANCH_NAME=$(BRANCH_PREFIX)/WorkItem-$WORK_ITEM_ID

    echo "Branch a ser criada: $BRANCH_NAME"

    az devops logout
  displayName: 'Criar nova branch no Git'