trigger: none
resources:
  webhooks:
    - webhook: AutoBranch     ### Webhook name
      connection: AutoBranch  ### Incoming webhook service connection name

variables:
  - group: GitHub Pipeline
  
steps:
- checkout: self
  persistCredentials: true
  
- script: |
    echo "${MY_JSON}"
  env:
    MY_JSON: ${{ convertToJson(parameters.AutoBranch.resource) }}
  displayName: "Resource json"

- script: |
    echo "##vso[task.setvariable variable=WORK_ITEM_ID]${WORK_ITEM_ID}"
    echo "##vso[task.setvariable variable=WORK_ITEM_TYPE]${WORK_ITEM_TYPE}"
    echo "##vso[task.setvariable variable=PARENT_WORK_ITEM_ID]${PARENT_WORK_ITEM_ID}"
    
    echo "${{ parameters.AutoBranch.resource.fields['Custom.Criarbranch'].newValue }}"
    # echo "${{ parameters.AutoBranch.resource.rev }}"

    # if [[ ${{ parameters.AutoBranch.resource.rev }} -ne 1 ]]; then
    #   createBranch=${{ parameters.AutoBranch.resource.fields['Custom.Criarbranch'].newValue }}
    # else
    #   createBranch=${{ parameters.AutoBranch.resource.fields['Custom.Criarbranch'] }}
    # fi

    if [[ -z "$WORK_ITEM_ID" ]]; then
      echo "##vso[task.logissue type=error]Work item ID not found."
      exit 1
    fi

    if [[ ! "$WORK_ITEM_TYPE" =~ ^($VALID_WORK_ITEM_TYPES)$ ]]; then
      echo "##vso[task.logissue type=error]Exit on Work item $WORK_ITEM_ID - Invalid type."
      exit 1
    fi

    # if [[ "$createBranch" == "false" ]]; then
    #   echo "##vso[task.logissue type=error]createBranch is set to false on work item $WORK_ITEM_ID."
    #   exit 1
    # fi
  env:
    WORK_ITEM_ID: ${{ parameters.AutoBranch.resource.id }}
    WORK_ITEM_TYPE: ${{ parameters.AutoBranch.resource.fields['System.WorkItemType'] }}
    PARENT_WORK_ITEM_ID: ${{ parameters.AutoBranch.resource.fields['System.Parent'] }}
  displayName: "Check incoming"

- script: |
    gh auth status
  env:
    GITHUB_TOKEN: $(GH_TOKEN)
  displayName: "Check Github authentication"
  
- script: |
    git config --global user.name $(GIT_USER_NAME)
    git config --global user.email $(GIT_USER_EMAIL)
  displayName: "Configure Git identity"

- script: |
    baseBrach=$(BASE_BRANCH)
    prTitle="AB#$WORK_ITEM_ID"

    if [[ "$WORK_ITEM_TYPE" == "Feature" ]]; then
      branchPrefix="F-"
    else
      if [[ -z "$PARENT_WORK_ITEM_ID" ]]; then
        exit 1
      fi 

      parentBranch="F-${PARENT_WORK_ITEM_ID}"

      if ! git ls-remote --exit-code --heads origin $parentBranch > /dev/null; then
        git fetch
        git checkout -b $parentBranch origin/$baseBrach
        git push origin $parentBranch
      fi 

      branchPrefix="T-"
      if [[ "$WORK_ITEM_TYPE" == "Impedimento" ]]; then
        branchPrefix="I-"
      fi

      prTitle="Fixed ${prTitle}"
      baseBrach="F-${PARENT_WORK_ITEM_ID}"
    fi

    newBranch="${branchPrefix}${WORK_ITEM_ID}"
    
    git fetch origin $baseBrach

    git checkout -b $newBranch origin/$baseBrach
    git push origin $newBranch

    if [[ "$MAKE_PR" == "true" ]]; then
      echo "Este é um arquivo criado automaticamente pela pipeline na branch $newBranch" > pipeline.txt
      
      git add pipeline.txt
      git commit -m "Pipeline"
      git push origin $newBranch

      gh pr create --base "$baseBrach" --head "$newBranch" --title "$prTitle" --body "Azure devops"
    fi
  env:
    GITHUB_TOKEN: $(GH_TOKEN)
  displayName: "Create branch and PR"