# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
resources:
  webhooks:
    - webhook: Incoming         ### Webhook name
      connection: Incoming    ### Incoming webhook service connection name

variables:
  - group: GitHub Pipeline
  
steps:
- checkout: self
  persistCredentials: true

- script: |
    gh auth status
  env:
    GITHUB_TOKEN: $(GH_TOKEN)
  displayName: "Verificar autenticação no GitHub"
  
- script: |
    git config --global user.name $(GIT_USER_NAME)
    git config --global user.email $(GIT_USER_EMAIL)
  displayName: "Configurar identidade Git"
  
- script: |
    echo "${MY_JSON}"
  env:
    MY_JSON: ${{ convertToJson(parameters.Incoming.resource) }}

- script: |
    if [ -n "${{ parameters.Incoming.resource.id }}" ]; then
      WORK_ITEM_ID=${{ parameters.Incoming.resource.id }}
    fi

    PREFIX="f-"
    BRANCH="${PREFIX}${WORK_ITEM_ID}"
    
    if git ls-remote --heads origin $BRANCH | grep $BRANCH; then
      echo "A branch $BRANCH já existe no remoto."
    else
      echo "Crindo a branch $BRANCH."

      git checkout -b $BRANCH

      echo "Este é um arquivo criado automaticamente pela pipeline." > pipeline.txt
      git add pipeline.txt
      git commit -m "Pipeline"
        
      git push origin $BRANCH

      TITLE="AB#$WORK_ITEM_ID"

      gh pr create --base main --head "$BRANCH" --title "$TITLE" --body "Descrição gerada pelo pipeline."
    fi
  env:
      GITHUB_TOKEN: $(GH_TOKEN)
  displayName: 'Criar nova branch no Git'